"""Extract exact supplied anatomy sprites and matching display-space silhouettes.

Usage: python tools/extract_inner_anatomy.py FinalPermanent.png FinalPrimary.png
Only the replacement inner rows are extracted; existing outer assets are untouched.
"""
import json
import sys
from pathlib import Path
from PIL import Image
from extract_permanent_teeth import transparent_cutout
from generate_tooth_silhouettes import display_size, silhouette_path

ROOT = Path(__file__).resolve().parents[1]
ROWS = {
    "permanent": [
        ([18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28],
         [72,168,261,347,425,510,590,677,769,857,936,1020,1100,1187,1281,1376], (80,237)),
        ([48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38],
         [66,160,254,348,432,515,599,680,763,843,925,1010,1095,1184,1280,1380], (595,714)),
    ],
    "primary": [
        ([17,16,55,54,53,52,51,61,62,63,64,65,26,27],
         [94,214,339,467,588,704,814,919,1026,1138,1245,1361,1474,1583], (267,397)),
        ([47,46,85,84,83,82,81,71,72,73,74,75,36,37],
         [94,213,339,456,576,692,801,907,1017,1128,1245,1365,1477,1598], (541,650)),
    ],
}

def main():
    metadata = {}
    for dentition, source in zip(ROWS, sys.argv[1:], strict=True):
        image = Image.open(source).convert("RGB")
        expected = (1448,1086) if dentition == "permanent" else (1672,941)
        if image.size != expected:
            raise ValueError(f"Unexpected {dentition} reference size {image.size}; expected {expected}")
        output = ROOT / "public/assets/images/teeth/inner" / dentition
        output.mkdir(parents=True, exist_ok=True)
        for numbers, centers, (top, bottom) in ROWS[dentition]:
            for i, number in enumerate(numbers):
                left = 0 if i == 0 else round((centers[i-1]+centers[i])/2)
                right = image.width if i == len(centers)-1 else round((centers[i]+centers[i+1])/2)
                sprite = transparent_cutout(image, (left,top,right,bottom))
                path = output / f"{number}.png"
                sprite.save(path)
                width = tuple(display_size(number,"crown"))[0]
                height = round(width * sprite.height / sprite.width)
                metadata[f"{dentition}:{number}"] = {
                    "width": width, "height": height,
                    "path": silhouette_path(path, (width,height)),
                    "asset": f"./assets/images/teeth/inner/{dentition}/{number}.png",
                }
    (ROOT / "public/js/inner-anatomy.js").write_text(
        "// Generated by tools/extract_inner_anatomy.py; do not edit by hand.\n"
        + "const INNER_ANATOMY=" + json.dumps(metadata,separators=(",",":")) + ";\n", encoding="utf-8")
    print(f"Extracted {len(metadata)} inner-view assets and silhouettes")

if __name__ == "__main__":
    main()
